"""Embed the authored Studio view in the Korean notebook for single-file upload.

Run after editing studio/ctp49906-kr/: python scripts/build_studio_bundle.py
CI uses --check to reject a stale embedded view. Only marked generated content
is replaced; notebook computations remain ordinary, readable Python cells.
"""

import argparse
import base64
import hashlib
import inspect
import json
import sys
import textwrap
import zlib
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT))
from src.studio_bundle import restore_studio_bundle

START = "# BEGIN GENERATED STUDIO BUNDLE"
END = "# END GENERATED STUDIO BUNDLE"
VIEW_ROOT = PROJECT / "studio" / "ctp49906-kr"
# Studio maintains workspace ignore rules itself; they are not authored assets.
FILES = ("explore/view.toml", "explore/index.html", "explore/style.css",
         "explore/main.js", "explore/AGENTS.md")


def generated_cell():
    files = {name: (VIEW_ROOT / name).read_text(encoding="utf-8") for name in FILES}
    raw = json.dumps({"schema": 1, "files": files}, ensure_ascii=False, sort_keys=True).encode()
    digest = hashlib.sha256(raw).hexdigest()
    payload = base64.b64encode(zlib.compress(raw, 9)).decode()
    literal = "\n".join(f'        "{part}"' for part in textwrap.wrap(payload, 100))
    function = inspect.getsource(restore_studio_bundle).replace(
        "def restore_studio_bundle(", "def _restore_studio_bundle(", 1
    )
    function = textwrap.indent(function.rstrip(), "    ")
    return f'''{START}
# Generated by scripts/build_studio_bundle.py; edit the tracked Studio sources.
@app.cell(hide_code=True)
def studio_files(mo):
{function}

    _payload = (
{literal}
    )
    try:
        _location = mo.notebook_location()
        if _location is None:
            raise ValueError("노트북을 저장한 뒤 셀을 다시 실행하세요.")
        studio_bundle_status = _restore_studio_bundle(_location, _payload, "{digest}")
        _message = "Studio 보기 파일을 준비했습니다. Molab의 Studio에서 explore 보기를 여세요."
        _kind = "info"
    except (ValueError, OSError) as _error:
        studio_bundle_status = {{"error": str(_error)}}
        _message = f"Studio 보기 준비 실패: {{_error}}"
        _kind = "warn"
    mo.callout(mo.md(_message), kind=_kind)
    return (studio_bundle_status,)
{END}'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = PROJECT / "CTP49906_avllm_molab_kr.py"
    source = path.read_text(encoding="utf-8")
    generated = generated_cell()
    if START in source:
        begin = source.index(START)
        end = source.index(END, begin) + len(END)
        updated = source[:begin] + generated + source[end:]
    else:
        marker = "\n\n@app.cell(hide_code=True)\ndef lab_intro"
        if marker not in source:
            raise SystemExit("Cannot locate lab_intro cell for the initial bundle insertion")
        updated = source.replace(marker, "\n\n" + generated + marker, 1)
    if args.check:
        if updated != source:
            raise SystemExit("Studio bundle is stale: run python scripts/build_studio_bundle.py")
        print("Studio bundle matches tracked sources")
    else:
        path.write_text(updated, encoding="utf-8")
        print("Updated Korean notebook Studio bundle")


if __name__ == "__main__":
    main()
