#!/usr/bin/env python3
"""Generate the native Molab HTML delivery from the canonical Korean notebook.

Only delivery metadata, prose, and the three form templates are changed. The
scientific cells remain copied from the canonical source. Forms stay in their
own cells, so a result update cannot recreate another form's unsubmitted draft.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
import textwrap
import tomllib


PROJECT = Path(__file__).resolve().parents[1]
CANONICAL = PROJECT / "CTP49906_avllm_molab_kr.py"
COMPANION = PROJECT / "CTP49906_avllm_molab_html_kr.py"
GENERATED_NOTICE = (
    "# Generated by scripts/build_molab_html.py from CTP49906_avllm_molab_kr.py.\n"
    "# Edit the canonical notebook or the generator, then regenerate this file.\n"
)

NATIVE_BOOTSTRAP = '''\
@app.cell(hide_code=True)
def studio_files():
    # Retain the setup dependency without installing or restoring Studio files.
    studio_bundle_status = {"delivery": "molab-native-html"}
    return (studio_bundle_status,)
'''

NAVIGATION = '''\
@app.cell(hide_code=True)
def molab_html_navigation(mo):
    mo.Html(r"""
    <style>
      .ctp-html-nav { display:flex; flex-wrap:wrap; gap:.5rem; padding:1rem 0; }
      .ctp-html-nav a { border:1px solid #94a3b8; border-radius:999px; padding:.45rem .9rem; text-decoration:none; font-weight:600; }
      .ctp-html-nav a:hover, .ctp-html-nav a:focus-visible { background:rgba(76,120,168,.14); outline:2px solid #4c78a8; outline-offset:2px; }
      .ctp-html-title { margin:0; font-size:1.6rem; line-height:1.35; }
      .ctp-html-description { margin:.5rem 0; line-height:1.65; }
      .ctp-html-anchor { scroll-margin-top:1.5rem; }
      @media (max-width:600px) { .ctp-html-nav a { flex:1 1 auto; text-align:center; } }
    </style>
    <header id="ctp-top" class="ctp-html-anchor">
      <h1 class="ctp-html-title">AVLLM 해석 가능성 실험실</h1>
      <p class="ctp-html-description">자신의 Molab GPU에서 설정을 바꾸고 실행합니다. 입력을 편집한 뒤 각 실험의 실행 버튼을 누르세요. 결과에는 마지막 실행에 사용한 설정이 표시됩니다.</p>
      <nav class="ctp-html-nav" aria-label="실습 섹션 이동">
        <a href="#ctp-guide">가이드</a>
        <a href="#ctp-diversity">다양성</a>
        <a href="#ctp-band">경로 차단</a>
        <a href="#ctp-tf">캡션 확률 변화</a>
        <a href="#ctp-evidence">실습 기록</a>
      </nav>
      <p class="ctp-html-description">처음에는 GPU를 켜고 Run all을 실행하세요. 위 링크는 페이지 안에서 이동합니다. 입력값은 실행 버튼을 누르기 전까지 결과에 적용되지 않습니다.</p>
    </header>
    """)
    return
'''

EVIDENCE_ANCHOR = '''\
@app.cell(hide_code=True)
def molab_html_evidence_anchor(mo):
    mo.Html('<div id="ctp-evidence" class="ctp-html-anchor"><h2>실습 기록</h2><p>실행 ID를 확인하고 관측과 해석을 남긴 뒤 Markdown과 JSON을 내려받으세요.</p><a href="#ctp-top">목차로 이동</a></div>')
    return
'''

# These templates change presentation only. The original batch children,
# validation functions, form options, and scientific consumers are preserved.
DIVERSITY_TEMPLATE = '''(
        '<section class="ctp-html-card" aria-label="프로브 다양성 입력">'
        '<p>설정 변경 후 실행을 눌러 적용하세요. 결과에는 마지막 실행에 사용한 설정이 표시됩니다.</p>'
        '<div class="ctp-html-fields">'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">클립</span>{clip}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">프레임</span>{nframes}</div>'
        '</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">프롬프트</span>{prompt}</div>'
        '<div class="ctp-html-fields">'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">녹아웃</span>{ko_enable}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">source → target</span>{ko_source} → {ko_target}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">레이어</span>{ko_layers}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">기준선도 함께 비교</span>{compare}</div>'
        '</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">고급 규칙</span>{ko_rules_text}</div>'
        '<p>녹아웃을 켠 상태에서 고급 규칙을 채우면 위의 단일 규칙보다 우선합니다. 비우면 위 설정을 사용합니다. '
        '<code>source,target,start,end</code> 형식으로 쓰고 여러 규칙은 <code>;</code>로 구분하세요.</p>'
        '<details><summary>업로드 · 도움말</summary>'
        '<p><code>업로드</code>를 골랐을 때만 파일을 넣으세요. 250 MiB / 120초 / 1080p 이하.</p>'
        '{video}<p>' + _hint + '</p></details>'
        '<p><a href="#ctp-top">목차로 이동</a></p></section>'
    )'''

BAND_TEMPLATE = '''(
        '<section class="ctp-html-card" aria-label="생성 경로 차단 입력">'
        '<p>설정 변경 후 실행을 눌러 적용하세요. 결과에는 마지막 실행에 사용한 설정이 표시됩니다.</p>'
        f'<p><strong>공통 입력</strong> · 클립 <code>{_band_escape(VIDEO_PATH.name).replace("{", "&#123;").replace("}", "&#125;")}</code> · {NFRAMES}프레임 · 캡션 상한 {MAX_NEW_TOKENS}토큰</p>'
        f'<p><strong>프롬프트</strong> {_band_escape(ATTENTION_PROMPT).replace("{", "&#123;").replace("}", "&#125;")}</p>'
        '<div class="ctp-html-fields">'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">generated → target</span>{target}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">레이어</span>{layers}</div>'
        '</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">실행 전 예상</span>{null_band} 캡션 변화가 작을 것으로 예상</div>'
        '<details><summary>구간 도움말</summary>'
        '<p>이 실행은 선택한 thinker 레이어 구간에서 generated 토큰이 선택한 타깃에 어텐션하는 경로를 금지합니다. '
        '체크박스에는 실행 전에 예상한 결과를 기록합니다. 체크 여부는 차단 규칙을 바꾸거나 이 실행을 대조군으로 지정하지 않습니다. 실행 후 실제 결과와 비교하세요.</p>'
        f'<p>끝 번호는 포함하지 않습니다. 이 thinker는 레이어가 <strong>{_band_layers}</strong>개입니다. '
        '클립·프롬프트·프레임 수는 파라미터 셀 값을 그대로 씁니다.</p></details>'
        '<p><a href="#ctp-top">목차로 이동</a></p></section>'
    )'''

TF_TEMPLATE = '''(
        '<section class="ctp-html-card" aria-label="캡션 확률 변화 입력">'
        '<p>이 실행에서 생성한 캡션을 고정하고, 선택한 직접 어텐션 연결을 차단하기 전후의 토큰 로그 확률을 비교합니다.</p>'
        '<p>설정 변경 후 실행을 눌러 적용하세요. 결과에는 마지막 실행에 사용한 설정이 표시됩니다.</p>'
        '<div class="ctp-html-fields">'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">클립</span>{clip}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">프레임</span>{nframes}</div>'
        '</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">프롬프트</span>{prompt}</div>'
        '<div class="ctp-html-fields">'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">answer → target</span>{target}</div>'
        '<div class="ctp-html-field"><span class="ctp-html-field-label">레이어</span>{layers}</div>'
        '</div>'
        '<details><summary>업로드 · 캡션 상한 · 도움말</summary>'
        '<p><strong>캡션 최대 토큰 수</strong> {max_new_tokens} — 상한에 닿으면 문장이 끊길 수 있습니다.</p>'
        '<p><code>업로드</code>를 골랐을 때만 파일을 넣으세요. 250 MiB / 120초 / 1080p 이하.</p>{video}'
        f'<p>이 thinker는 레이어가 <strong>{_n_layers}</strong>개입니다. 끝 번호는 포함하지 않습니다.</p>'
        '<p>무음 대조군은 원본과 같은 영상에 디지털 무음 오디오를 넣은 클립입니다. 오디오 트랙과 토큰은 그대로 존재합니다. '
        '같은 설정으로 두 클립을 각각 실행하고, 캡션 내용과 Δ를 함께 비교하세요.</p>'
        '<p>같은 캡션은 한 실행의 기준선·차단 비교 안에서 고정됩니다. 클립·프롬프트·생성 상한이 달라지면 캡션도 달라질 수 있으며, '
        '토큰당 평균을 비교해도 내용·언어 차이가 통제되지는 않습니다. answer는 채점할 캡션 토큰입니다. '
        '첫 캡션 토큰은 마지막 프롬프트 위치에서 예측되므로 answer만 차단하는 규칙의 직접 영향을 받지 않습니다. '
        'query_text에는 질문뿐 아니라 채팅 구조와 특수 토큰도 포함됩니다.</p></details>'
        '<p><a href="#ctp-top">목차로 이동</a></p></section>'
    )'''


def _inline_form_styles(template: str) -> str:
    """Keep styles with the batch markup rendered inside its shadow root.

    This transforms only the trusted HTML literals above, never notebook code or
    user text. Inline declarations also avoid CSS braces in batch's format pass.
    """
    styles = {
        "ctp-html-card": "border:1px solid #94a3b8;border-radius:16px;padding:clamp(1rem,3vw,1.75rem);overflow-wrap:anywhere",
        "ctp-html-fields": "display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:1rem;margin:1rem 0",
        "ctp-html-field": "min-width:0",
        "ctp-html-field-label": "display:block;font-weight:650;margin-bottom:.35rem",
    }
    if template.count('class="ctp-html-card"') != 1:
        raise ValueError("Expected one HTML card in each native form template")
    for name, style in styles.items():
        template = template.replace(f'class="{name}"', f'class="{name}" style="{style}"')
    for tag, style in {
        "p": "line-height:1.65;margin:.75rem 0",
        "details": "margin-top:1rem;border-top:1px solid #94a3b8;padding-top:.75rem",
        "summary": "cursor:pointer;font-weight:650;padding:.3rem 0",
    }.items():
        template = template.replace(f"<{tag}>", f'<{tag} style="{style}">')
    return template


def _position(source: str, node: ast.AST, *, end: bool = False) -> int:
    """AST columns count UTF-8 bytes; convert to Python string offsets."""
    lines = source.splitlines(keepends=True)
    line = getattr(node, "end_lineno" if end else "lineno")
    column = getattr(node, "end_col_offset" if end else "col_offset")
    return sum(map(len, lines[:line - 1])) + len(lines[line - 1].encode()[:column].decode())


def _replace_nodes(source: str, edits: list[tuple[ast.AST, str]]) -> str:
    spans = sorted((_position(source, node), _position(source, node, end=True), text)
                   for node, text in edits)
    for left, right in zip(spans, spans[1:]):
        if left[1] > right[0]:
            raise ValueError("Overlapping generated source changes")
    for start, end, replacement in reversed(spans):
        source = source[:start] + replacement + source[end:]
    return source


def _only(items, description):
    items = list(items)
    if len(items) != 1:
        raise ValueError(f"Expected one {description}, found {len(items)}")
    return items[0]


def _mo_call(node: ast.AST, method: str) -> bool:
    return (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
            and isinstance(node.func.value, ast.Name) and node.func.value.id == "mo"
            and node.func.attr == method)


def _markdown_literal(text: str) -> str:
    if '"""' in text:
        raise ValueError("Delivery markdown contains a triple quote; review its source formatting")
    return 'r"""\n' + textwrap.indent(text.strip(), "    ") + '\n    """'


def _assignment(cell: ast.FunctionDef, name: str) -> ast.Assign:
    return _only((node for node in cell.body if isinstance(node, ast.Assign)
                  and any(isinstance(target, ast.Name) and target.id == name
                          for target in node.targets)), f"{cell.name}.{name} assignment")


def _metadata(source: str) -> str:
    lines = source.splitlines(keepends=True)
    if lines[0].strip() != "# /// script":
        raise ValueError("Canonical notebook must start with PEP 723 metadata")
    end = next(index for index, line in enumerate(lines[1:], 1) if line.strip() == "# ///")
    metadata = tomllib.loads("".join(line[2:] if line.startswith("# ") else line[1:]
                                   for line in lines[1:end]))
    dependencies = [item for item in metadata["dependencies"] if not item.startswith("marimo-studio")]
    # Keep scientific package declarations unchanged; managed Molab setup reuses
    # its installed torch instead of starting a separate dependency sandbox.
    header = ["# /// script\n", f'# requires-python = "{metadata["requires-python"]}"\n', "# dependencies = [\n"]
    header.extend(f'#     "{item}",\n' for item in dependencies)
    header.extend(["# ]\n", "# ///\n", "\n", GENERATED_NOTICE])
    return "".join(header + lines[end + 1:])


def generate(source: str) -> str:
    source = _metadata(source)
    begin = source.index("# BEGIN GENERATED STUDIO BUNDLE")
    end = source.index("# END GENERATED STUDIO BUNDLE", begin) + len("# END GENERATED STUDIO BUNDLE")
    source = source[:begin] + NATIVE_BOOTSTRAP + "\n\n" + NAVIGATION.rstrip() + source[end:]
    tree = ast.parse(source)
    cells = {node.name: node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name != "_"}
    edits: list[tuple[ast.AST, str]] = []

    for cell_name, variable, template in [
        ("diversity_form", "_template", DIVERSITY_TEMPLATE),
        ("tf_form", "_tf_template", TF_TEMPLATE),
    ]:
        cell = cells[cell_name]
        edits.append((_assignment(cell, variable).value, _inline_form_styles(template)))
        call = _only((node for node in ast.walk(cell) if _mo_call(node, "md")
                      and len(node.args) == 1 and isinstance(node.args[0], ast.Name)
                      and node.args[0].id == variable), f"{cell_name} template renderer")
        edits.append((call.func, "mo.Html"))

    band = cells["band_form"]
    call = _only((node for node in ast.walk(band) if _mo_call(node, "md")), "band form template")
    edits.extend([(call.func, "mo.Html"), (call.args[0], _inline_form_styles(BAND_TEMPLATE))])

    # A batch/form retains hidden copies of its HTML template. Navigation IDs
    # must live outside that cloned markup, or a hash link targets a hidden copy.
    # Keep the native form object itself in vstack so its children stay alive.
    for name, controls, anchor, title in [
        ("diversity_form", "ko_controls", "ctp-diversity", "다양성"),
        ("band_form", "band_controls", "ctp-band", "경로 차단"),
        ("tf_form", "tf_controls", "ctp-tf", "캡션 확률 변화"),
    ]:
        display = _only((node for node in cells[name].body if isinstance(node, ast.Expr)
                         and isinstance(node.value, ast.Name) and node.value.id == controls),
                        f"{name} native form display")
        heading = f'<div id="{anchor}" class="ctp-html-anchor"><h2>{title}</h2></div>'
        edits.append((display.value, f"mo.vstack([mo.Html({heading!r}), {controls}])"))

    intro = _only((node for node in ast.walk(cells["lab_intro"]) if _mo_call(node, "md")), "intro markdown")
    intro_text = ast.literal_eval(intro.args[0])
    old = "Studio에서는 ‘실험실’의 ‘다양성’, ‘경로 차단’, ‘캡션 확률 변화’와 ‘실습 기록’ 탭을 사용하세요."
    if intro_text.count(old) != 1:
        raise ValueError("Canonical intro navigation text changed; review native delivery copy")
    intro_text = '<div id="ctp-guide" class="ctp-html-anchor"></div>\n\n' + textwrap.dedent(intro_text).replace(
        old, "위쪽 목차에서 ‘다양성’, ‘경로 차단’, ‘캡션 확률 변화’, ‘실습 기록’으로 이동하세요."
    )
    edits.append((intro.args[0], _markdown_literal(intro_text)))

    setup = _only((node for node in ast.walk(cells["molab_setup_note"]) if _mo_call(node, "md")), "setup markdown")
    setup_text = ast.literal_eval(setup.args[0])
    old = "4. 발표/App view에서는 코드 없이 읽을 수 있습니다. 코드 편집은 고급 탐색 단계에서 합니다."
    if setup_text.count(old) != 1:
        raise ValueError("Canonical setup navigation text changed; review native delivery copy")
    setup_text = textwrap.dedent(setup_text).replace(
        old, "4. 현재 노트북의 발표/App view에서 코드 없이 탐색할 수 있습니다. 목차로 이동해 입력을 바꾸고 실행 버튼을 누르세요. 코드 편집은 고급 탐색 단계에서 합니다."
    )
    edits.append((setup.args[0], _markdown_literal(setup_text)))

    status = cells["studio_status"]
    for node in ast.walk(status):
        if isinstance(node, ast.Constant) and node.value == "**라이브 모드** · ▶로 새 실험을 실행합니다.":
            edits.append((node, repr("**Molab 내장 HTML · 라이브 모드** · 준비가 끝나면 ▶로 새 실험을 실행합니다.")))
        elif isinstance(node, ast.Constant) and node.value == "**재생 모드** · 저장 결과만 표시합니다.":
            edits.append((node, repr("**Molab 내장 HTML · 재생 모드** · 저장 결과만 표시합니다.")))

    app = _only((node for node in tree.body if isinstance(node, ast.Assign)
                 and any(isinstance(target, ast.Name) and target.id == "app" for target in node.targets)), "app assignment")
    if not isinstance(app.value, ast.Call):
        raise ValueError("Canonical app is no longer a direct constructor")
    width = _only((keyword for keyword in app.value.keywords if keyword.arg == "width"), "app width")
    edits.append((width.value, repr("full")))

    for cell in (node for node in tree.body if isinstance(node, ast.FunctionDef)):
        for decorator in cell.decorator_list:
            reference = decorator.func if isinstance(decorator, ast.Call) else decorator
            if (isinstance(reference, ast.Attribute) and isinstance(reference.value, ast.Name)
                    and reference.value.id == "app" and reference.attr == "cell"):
                if isinstance(decorator, ast.Call):
                    options = [keyword for keyword in decorator.keywords if keyword.arg == "hide_code"]
                    if options:
                        edits.append((options[0].value, "True"))
                    else:
                        existing = ast.get_source_segment(source, decorator)
                        edits.append((decorator, existing[:-1] + (", " if decorator.args or decorator.keywords else "") + "hide_code=True)"))
                else:
                    edits.append((decorator, "app.cell(hide_code=True)"))

    source = _replace_nodes(source, edits)
    tree = ast.parse(source)
    verdict = _only((node for node in tree.body if isinstance(node, ast.FunctionDef)
                    and node.name == "verdict_panel"), "verdict cell")
    start = _position(source, verdict.decorator_list[0]) - 1  # include @
    source = source[:start] + EVIDENCE_ANCHOR + "\n\n" + source[start:]
    ast.parse(source)
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=CANONICAL)
    parser.add_argument("--output", type=Path, default=COMPANION)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.source.resolve() == args.output.resolve():
        parser.error("Source and output must be different files")
    expected = generate(args.source.read_text(encoding="utf-8"))
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
            print(f"Native Molab HTML companion is stale: {args.output}")
            return 1
        print(f"Native Molab HTML companion is current: {args.output}")
    else:
        args.output.write_text(expected, encoding="utf-8")
        print(f"Generated native Molab HTML companion: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
